site_name: My first Phyton website
#site_url: https://milastam.com/
nav:
  - Home: index.md
  - Agile: https://milagro2.github.io./Agile.html
  - Projects:
      - Project 1: project1.md
      - Project 2: project2.md

theme: material
