site_name: My first Phyton website
#site_url: https://milastam.com/
nav:
  - Home: index.md
  - Agile: https://milagro2.github.io./Agile.html
  - DevOps: DevOps.html
  - Goals: goals.md
  - Project: projects.md

theme: mkdocs
