name: Deploy stuff

on:
  push:
    branches:
      - master

jobs:
  update_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Install MkDocs
        run: |
          pip install mkdocs

      - name: Deploy MkDocs
        run: |
          mkdocs gh-deploy
 
