name: Deploy stuff

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - project4-variablechecker
# dont forget to change /\ to master when merged (;

jobs:
  update_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch latest branch info
        run: git fetch

      - name: Deploy MkDocs
        run: mkdocs gh-deploy
