name: Run Python Script

on:
  push:
    branches:
<<<<<<< HEAD
      - variable-defined

=======
      - master
>>>>>>> master
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

<<<<<<< HEAD
    - name: Run VariableChecker.py
      run: python projects/project2/VariableChecker.py

    - name: Run WordFinder.py
      run: python projects/project2/WordFinder.py
 
=======
    - name: Run namechecker script GoodName.py
      run: python projects/project3/GoodName.py
      
>>>>>>> master
